#pragma once

#include "TransformComponent.h"
#include "NameComponent.h"
#include "SpriteComponent.h"
#include "CameraComponent.h"
#include "AudioComponent.h"
#include "TextComponent.h"
#include "CanvasRendererComponent.h"
#include "MeshFilterComponent.h"
#include "MeshRendererComponent.h"
#include "SkinnedMeshRendererComponent.h"
#include "AnimatorComponent.h"
#include "LightComponent.h"
#include "ScriptComponent.h"
#include "CubeRenderComponent.h"
#include "MaterialComponent.h"

#include "BoxColliderComponent.h"
#include "CapsuleColliderComponent.h"
#include "SphereColliderComponent.h"
#include "RigidbodyComponent.h"
#include "CharacterControllerComponent.h"

#include "OctreeGeneratorComponent.h"
#include "ParticleComponent.h"