#pragma once

/******************************************************************/
/*!
\file      OctreeGrid.h
\author    Yeo See Kiat Raymond, seekiatraymond.yeo, 2301268
\par       seekiatraymond.yeo@digipen.edu
\date      October 3, 2025
\brief     This file contains the grid generated by the Octree system,
			holding the graph to be accessed and determines how the
			octree should be created.


Copyright (C) 2025 DigiPen Institute of Technology.
Reproduction or disclosure of this file or its contents without the
prior written consent of DigiPen Institute of Technology is prohibited.
*/
/********************************************************************/

#ifndef OCTREEGRID_H
#define OCTREEGRID_H

#include "Config/pch.h"
#include "ECS/ECS.h"

#include "../../Graphics/GraphicsManager.h"
#include "Graph.h"

namespace Octrees {
	struct Octree {
		OctreeNode root;
		Bounds bounds;
		Graph graph;

		std::vector<OctreeNode> emptyLeaves;

		Octree();
		Octree(float minNodeSize, Graph _graph);
		//void GetEmptyLeaves(OctreeNode node);
		void GetEmptyLeaves(OctreeNode* node);
		void CreateTree(float minNodeSize);
		void CalculateBounds();
		void GetEdges();

		OctreeNode FindClosestNode(glm::vec3 position);
		OctreeNode FindClosestNode(OctreeNode node, glm::vec3 position);
	};
}

#endif